-- FinCompare BD Supabase Setup Script
-- Run this in your Supabase SQL Editor to create tables and seed initial data.
-- 1. Create Tables
CREATE TABLE IF NOT EXISTS credit_cards (
    id SERIAL PRIMARY KEY,
    bank TEXT NOT NULL,
    name TEXT NOT NULL,
    highlight TEXT,
    rating NUMERIC(2, 1),
    reviews INTEGER,
    annual_fee TEXT,
    fee_waived_condition TEXT,
    interest_rate TEXT,
    features JSONB,
    documents JSONB,
    eligibility JSONB,
    color TEXT,
    badge_color TEXT,
    is_popular BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS loans (
    id SERIAL PRIMARY KEY,
    bank TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    highlight TEXT,
    rating NUMERIC(2, 1),
    reviews INTEGER,
    processing_fee TEXT,
    fee_details TEXT,
    interest_rate TEXT,
    features JSONB,
    documents JSONB,
    eligibility JSONB,
    color TEXT,
    badge_color TEXT,
    is_popular BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS deposits (
    id SERIAL PRIMARY KEY,
    bank TEXT NOT NULL,
    name TEXT NOT NULL,
    highlight TEXT,
    rating NUMERIC(2, 1),
    reviews INTEGER,
    min_deposit TEXT,
    tenure TEXT,
    interest_rate TEXT,
    features JSONB,
    color TEXT,
    badge_color TEXT,
    is_popular BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS shariah_cards (
    id SERIAL PRIMARY KEY,
    bank TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT,
    rating NUMERIC(2, 1),
    reviews INTEGER,
    annual_fee TEXT,
    features JSONB,
    facilities JSONB,
    documents JSONB,
    eligibility JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- 2. Insert Dummy Data
-- Insert Credit Cards
INSERT INTO credit_cards (
        bank,
        name,
        highlight,
        rating,
        reviews,
        annual_fee,
        fee_waived_condition,
        interest_rate,
        features,
        documents,
        eligibility,
        color,
        badge_color,
        is_popular
    )
VALUES (
        'Eastern Bank PLC',
        'Visa Signature Card',
        'Best for Travel & Lounge',
        4.9,
        128,
        '৳ 10,000',
        'Waived on 18 transactions',
        '20% p.a.',
        '["Unlimited free access to Balaka Lounge", "Complimentary Priority Pass", "B1G1 free buffer at 5-star hotels", "Up to 50% discount at partner outlets"]',
        '["National ID Card (NID) copy", "Last 6 months'' bank statements", "Latest Salary Certificate / Pay Slip", "Passport size photograph"]',
        '["Minimum age: 21 years", "Minimum monthly income: ৳ 50,000", "Must be a citizen of Bangladesh"]',
        'from-blue-600 to-indigo-800',
        'bg-blue-100 text-blue-700',
        true
    ),
    (
        'City Bank',
        'AMEX Platinum',
        'Premium Lifestyle',
        4.8,
        95,
        '৳ 15,000',
        'Not Applicable',
        '20% p.a.',
        '["B1G1 free stay at luxury resorts", "Complimentary City Bank Amex Lounge", "Triple Membership Rewards points", "Comprehensive travel insurance"]',
        '["National ID Card (NID)", "Last 6 months'' bank statements", "Recent salary certificate or Trade License", "Recent utility bill copy"]',
        '["Minimum age: 21 years", "Salaried executive or self-employed professional", "Minimum monthly net income: ৳ 1,20,000"]',
        'from-slate-800 to-black',
        'bg-slate-100 text-slate-700',
        false
    ),
    (
        'Standard Chartered',
        'Signature Credit Card',
        'Best for Dining & Cashback',
        4.7,
        210,
        '৳ 8,000',
        'First year free',
        '20% p.a.',
        '["Max cashback on dining & groceries", "Buy 1 Get 1 free movie tickets at Blockbuster", "Airport lounge access worldwide", "Zero over-limit fee"]',
        '["Valid NID / Passport Copy", "Last 6 months'' account statement", "Income statement / Salary certificate", "TIN Certificate"]',
        '["Minimum age 21 years", "Minimum monthly income: ৳ 30,000", "Standard Chartered Account holder preferred"]',
        'from-emerald-600 to-teal-800',
        'bg-emerald-100 text-emerald-700',
        false
    );
-- Insert Loans
INSERT INTO loans (
        bank,
        name,
        category,
        highlight,
        rating,
        reviews,
        processing_fee,
        fee_details,
        interest_rate,
        features,
        documents,
        eligibility,
        color,
        badge_color,
        is_popular
    )
VALUES (
        'BRAC Bank',
        'Disha Personal Loan',
        'Personal Loan',
        'Quick Processing',
        4.8,
        312,
        '0.5%',
        'Up to ৳ 5,000',
        '9.5% p.a.',
        '["Fast approval process within 3 days", "No hidden charges or early settlement fees", "Flexible repayment terms up to 60 months", "Loan amount up to ৳ 20 Lakhs"]',
        '["National ID Card (NID) – front & back", "Last 3 months'' bank statements", "Latest 2 months salary slips", "Employer letter confirming employment", "Recent utility bill (proof of address)"]',
        '["Minimum age: 22 years; Maximum age: 60 years at maturity", "Must be a confirmed/permanent employee for at least 1 year", "Minimum monthly income: ৳ 25,000", "Must have an active BRAC Bank account", "No prior loan defaults with any bank"]',
        'from-blue-600 to-indigo-800',
        'bg-blue-100 text-blue-700',
        true
    ),
    (
        'City Bank',
        'City Solution Loan',
        'Personal Loan',
        'Lowest Rate',
        4.6,
        184,
        '1%',
        'Standard processing',
        '9.0% p.a.',
        '["Competitive interest rate for salary accounts", "Minimal documentation required", "Top-up facility after 6 months", "Loan amount up to ৳ 15 Lakhs"]',
        '["National ID Card (NID)", "Last 3 months'' bank statements", "Recent salary certificate", "Passport-size photographs (2 copies)", "TIN certificate (for loans above ৳ 5 Lakhs)"]',
        '["Minimum age: 21 years; Maximum: 57 years", "Salaried individuals with at least 6 months tenure", "Minimum monthly net income: ৳ 20,000", "Preferred: existing City Bank account holders", "Clean CIB (Credit Information Bureau) report"]',
        'from-emerald-600 to-teal-800',
        'bg-emerald-100 text-emerald-700',
        false
    ),
    (
        'Standard Chartered',
        'Home Dream Loan',
        'Home Loan',
        'Premium Lending',
        4.9,
        420,
        '0.5%',
        'Min. ৳ 10,000',
        '8.5% p.a.',
        '["Up to 25 years repayment tenure", "Partial prepayment allowed without penalty", "Automated EMI tracking", "Financing up to ৳ 2 Crores"]',
        '["National ID Card (NID) and Passport (if applicable)", "Registered sale deed or allotment letter of the property", "Approved building plan and RAJUK clearance", "Last 6 months'' bank statements", "Income tax return (last 2 years)", "Property valuation report from approved surveyor"]',
        '["Minimum age: 25 years; Maximum: 65 years at loan maturity", "Minimum monthly income: ৳ 75,000 (salaried) or ৳ 1,50,000 (self-employed)", "Applicant must have clear land ownership documents", "Property must be within RAJUK/CDA approved area", "Debt-to-income ratio must not exceed 50%"]',
        'from-slate-800 to-black',
        'bg-slate-100 text-slate-700',
        true
    ),
    (
        'DBBL',
        'Aashiyana Home Loan',
        'Home Loan',
        'Best for Core Banking',
        4.5,
        145,
        '1%',
        'Capped at ৳ 15,000',
        '8.8% p.a.',
        '["Discounted rates for active DBBL account holders", "Easy transfer of existing home loans", "Zero application fee", "Financing up to ৳ 1.5 Crores"]',
        '["National ID Card (NID)", "All original property ownership documents (chain of title)", "RAJUK / Municipality approved plan", "Last 6 months'' DBBL account statements", "Salary certificate or business trade license"]',
        '["Minimum age: 23 years; Maximum: 62 years at maturity", "Minimum monthly income: ৳ 50,000", "Must have an active DBBL account for at least 6 months", "Property must be located within major city corporation areas", "No outstanding overdue loans with DBBL"]',
        'from-purple-600 to-violet-800',
        'bg-purple-100 text-purple-700',
        false
    ),
    (
        'Eastern Bank PLC',
        'EBL Auto Loan',
        'Auto Loan',
        'Best for New Cars',
        4.7,
        210,
        '1%',
        'Of loan amount',
        '9.0% p.a.',
        '["Partner discounts available with top dealerships", "Up to 100% financing for specific brand new models", "Dedicated relationship manager", "Financing up to ৳ 40 Lakhs"]',
        '["National ID Card (NID)", "Proforma invoice from registered car dealer", "Last 6 months'' bank statements", "Driving license (for personal use)", "Salary certificate or trade license"]',
        '["Minimum age: 21 years; Maximum: 60 years at maturity", "Minimum monthly income: ৳ 40,000 (salaried) or ৳ 80,000 (self-employed)", "Vehicle must be brand new or reconditioned (not older than 5 years)", "Clear CIB report with no classified loans", "Applicant must be a Bangladeshi national"]',
        'from-amber-500 to-orange-700',
        'bg-amber-100 text-amber-800',
        true
    ),
    (
        'SME Foundation',
        'Entrepreneur Growth',
        'Business Loan',
        'Govt. Subsidized',
        4.9,
        580,
        '0%',
        'Subsidized',
        '4.0% p.a.',
        '["Highly subsidized interest rate for SME owners", "Focus on women entrepreneurs (2.5% rate)", "Grace period of up to 6 months", "Working capital up to ৳ 50 Lakhs"]',
        '["National ID Card (NID) of proprietor/directors", "Trade license (latest renewed copy)", "TIN certificate and last 2 years'' tax returns", "Last 12 months'' bank statements", "Business plan and financial projections", "IRC/ERC (for export-import businesses)"]',
        '["Must be a registered Bangladeshi SME enterprise", "Business must be operational for at least 1 year", "Annual turnover should not exceed ৳ 30 Crores", "Women entrepreneurs receive priority & lower rate (2.5%)", "No classified loan record in CIB report"]',
        'from-indigo-600 to-blue-900',
        'bg-indigo-100 text-indigo-700',
        true
    );
-- Insert Deposits (DPS/FDR)
INSERT INTO deposits (
        bank,
        name,
        highlight,
        rating,
        reviews,
        min_deposit,
        tenure,
        interest_rate,
        features,
        color,
        badge_color,
        is_popular
    )
VALUES (
        'BRAC Bank',
        'Millionaire Scheme',
        'Best for Long Term',
        4.9,
        342,
        '৳ 500 / month',
        '3 - 10 Years',
        '8.50% p.a.',
        '["Flexible monthly installments", "Loan facility up to 90%", "Auto debit facility available", "Highest return on maturity"]',
        'from-teal-600 to-emerald-800',
        'bg-teal-100 text-teal-700',
        true
    ),
    (
        'IDLC Finance',
        'Fixed Term Deposit',
        'Highest FDR Rates',
        4.8,
        890,
        '৳ 10,000',
        '3 Months - 5 Years',
        '9.00% p.a.',
        '["Monthly/Quarterly/Annual interest payout", "Premature encashment facility", "Auto renewal option", "Senior citizen gets extra 0.25%"]',
        'from-indigo-600 to-blue-800',
        'bg-indigo-100 text-indigo-700',
        false
    ),
    (
        'City Bank',
        'DPS Plus',
        'Best Value',
        4.7,
        156,
        '৳ 1,000 / month',
        '1 - 10 Years',
        '8.25% p.a.',
        '["Bonus interest upon maturity", "Free life insurance coverage", "Can be opened via Citytouch app", "Overdraft facility available"]',
        'from-rose-600 to-red-800',
        'bg-rose-100 text-rose-700',
        false
    );
-- Insert Shariah Cards (Islamic Hub)
INSERT INTO shariah_cards (
        bank,
        name,
        type,
        rating,
        reviews,
        annual_fee,
        features,
        facilities,
        documents,
        eligibility
    )
VALUES (
        'The City Bank PLC',
        'City Islamic Platinum Card',
        'Ujrah Based',
        4.8,
        142,
        '৳ 2,500',
        '["Zero Riba (Interest)", "Compliant with Islamic Shariah", "Free access to City Bank VIP lounge"]',
        '["Dedicated 24/7 customer service", "Supplementary card free of cost", "Special discounts on Umrah packages", "Free access to City Bank VIP lounge"]',
        '["NID Copy and Passport Size Photograph", "Salary Certificate / Pay Slip", "Bank Statement for last 6 months", "TIN Certificate"]',
        '["Minimum age 21 years", "Minimum income ৳ 30,000/month", "Must be a citizen of Bangladesh"]'
    ),
    (
        'Standard Chartered Bank',
        'Saadiq Platinum Credit Card',
        'Ujrah Based',
        4.7,
        215,
        '৳ 3,000',
        '["Globally accepted", "Halal dining & lifestyle privileges", "Sadaqah (Charity) point redemption"]',
        '["Globally accepted at over 30 million establishments", "Halal dining & lifestyle privileges", "Sadaqah (Charity) point redemption mapping", "Auto payment facility from Saadiq account"]',
        '["Valid NID / Passport Copy", "Latest Salary Certificate", "Last 6 months Bank Statement", "Recent utility bill copy"]',
        '["Minimum age 21 years", "Minimum income ৳ 50,000/month", "Salaried executive or self-employed professional"]'
    ),
    (
        'Al-Arafah Islami Bank',
        'AIBL Khidmah Credit Card',
        'Mudaraba Based',
        4.5,
        98,
        '৳ 1,500',
        '["Lowest Ujrah fee", "Dual currency", "Discounts at partner hospitals"]',
        '["Lowest Ujrah fee in the market", "Dual currency (BDT & USD) supported", "Discounts at partner hospitals and diagnostic centers", "Cash withdrawal facility up to 50% of limit"]',
        '["NID Copy", "2 copies of Passport Size Photograph", "Income statement / Salary certificate", "TIN Certificate"]',
        '["Minimum age 18 years", "Minimum income ৳ 20,000/month", "AIBL Account Holder preferred"]'
    );